version: '3'
services:
  react-docker-env:
    image: react-docker-env:1.0.2
    ports: 
      - 3000:3000
    env_file: 
      - .env
    environment: 
      # - REACT_APP_VERSION=1.0.2
      - REACT_APP_TEST_ENV=MY_ENV_FROM_DOCKER_COMPOSE